### ISSUE TITLE
[FEATURE] Add tsv (tab separated) as save format

### ISSUE THREAD

**Issue by keiranmraine** [fugue-project/fugue#331] opened 2022-06-17 14:00 UTC
**Is your feature request related to a problem? Please describe.**
TSV files are used extensively in bioinformatic spaces.

**Describe the solution you'd like**
Support `SAVE` direct to tsv.

**Describe alternatives you've considered**
Outputter following `SAVE AND LOAD`

**Comment by kvnkho** [comment] 2022-06-17 15:22
Just adding notes, I was testing this and the issue is we don't allow filename with `.tsv` extension. We should support it. For a lot of the engines, it's jut changing the delimiter of the method to read csvs

**Comment by goodwanghan** [comment] 2022-06-18 05:22
![image](https://user-images.githubusercontent.com/21092479/174424070-52e0d217-7257-4114-b8ac-6de6039ce90e.png)
 
We can support TSV already

**Comment by keiranmraine** [comment] 2022-06-20 08:15
FYI, this doesn't handle windows file paths:

```console
File <string>:1
    "c:\Users\XXX\cleaned.tsv"
                                                                                                      ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
```

I had to do:

```python
fe_output = f_output.replace("\\", "\\\\")
```

```
%%fsql
SELECT df_links.uuid, df_pcawg.*
    FROM df_pcawg
    INNER JOIN df_links ON df_pcawg.icgc_donor_id = df_links.DO
SAVE OVERWRITE CSV "{{fe_output}}" (sep="\t", header=TRUE)
```

**Comment by keiranmraine** [comment] 2022-06-20 08:20
Changing the last directive to `SAVE AND USE OVERWRITE CSV "{{fe_output}}" (sep="\t", header=TRUE)` results in an error:

```console
File c:\Users\XXX\.venv\lib\site-packages\fugue\workflow\workflow.py:1518, in FugueWorkflow.run(self, *args, **kwargs)
   1516         if ctb is None:  # pragma: no cover
   1517             raise
-> 1518         raise ex.with_traceback(ctb)
   1519     self._computed = True
   1520 return DataFrames(
   1521     {
...
    231         pdf = _safe_load_csv(
    232             p.uri, **{"index_col": False, "header": None, "names": columns, **kw}
    233         )

ValueError: columns must be set if without header
```

**Comment by goodwanghan** [comment] 2022-06-20 17:19
> FYI, this doesn't handle windows file paths:
> 
> ```
> File <string>:1
>     "c:\Users\XXX\cleaned.tsv"
>                                                                                                       ^
> SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
> ```
> 
> I had to do:
> 
> ```python
> fe_output = f_output.replace("\\", "\\\\")
> ```
> 
> ```
> %%fsql
> SELECT df_links.uuid, df_pcawg.*
>     FROM df_pcawg
>     INNER JOIN df_links ON df_pcawg.icgc_donor_id = df_links.DO
> SAVE OVERWRITE CSV "{{fe_output}}" (sep="\t", header=TRUE)
> ```

This is actually a correct behavior. It may be tricky to understand, but let me use a native python code to illustrate:
![image](https://user-images.githubusercontent.com/21092479/174651651-56d13f33-2c8c-450a-a525-22019d0e1c81.png)

The `eval` here tries to parse the expression with double quotes, which is very similar to `fsql`. And you see I can reproduce the error you had. Let me know if you can understand what I try to explain.

**Comment by goodwanghan** [comment] 2022-06-20 17:28
@keiranmraine please see the issue 332 ^^^

**Comment by goodwanghan** [comment] 2022-07-10 06:54
Closing

**Closed by goodwanghan** 2022-07-10 06:54 UTC
