### ISSUE TITLE
[BUG] Save to parquet throws error on NativeExecutionEngine with pandas < 1.0

### ISSUE THREAD

**Issue by goodwanghan** [fugue-project/fugue#45] opened 2020-09-22 23:08 UTC
**Minimal Code To Reproduce**

```python
from fugue import FugueWorkflow

with FugueWorkflow() as dag:
    dag.df([[0]],"a:int").save("/tmp/1.parquet")
```

**Describe the bug**
For pandas>=1, it works fine, for pandas<1 it complains the `schema` argument is duplicated

**Expected behavior**
It should work for pandas < 1

**Environment (please complete the following information):**
 - Backend: pandas
 - Backend version: 0.25.0
 - Python version: 3.6.9
 - OS: linux/windows linux

**Comment by kvnkho** [comment] 2020-10-03 06:14
Replicated the issue on Linux....but it's actually working fine on Windows for me with the same versions. I can also load it fine on Windows. 

Will explore this issue on Linux.

**Comment by kvnkho** [comment] 2020-10-04 18:43
I successfully replicated the issue on both Windows and Linux. The error printed out is:

`TypeError: __init__() got multiple values for argument 'schema'`

The `NaiveExecutionEngine` that `FugueWorkflow` uses by default uses pandas `to_parquet` to write out
a parquet file. The code looks like this:

```python
def _save_parquet(df: LocalDataFrame, p: FileParser, **kwargs: Any) -> None:
    df.as_pandas().to_parquet(
        p.uri, **{"engine": "pyarrow", "schema": df.schema.pa_schema, **kwargs}
    )
```

Note `schema` is passed to this method as a keyword argument. Now we need to see how pandas accepts the `schema` argument.

There was a change from pandas 0.25 to pandas 1.0. Reading this [issue](https://github.com/pandas-dev/pandas/issues/30189)
pandas 0.25 did not have support to enforce a schema when writing a parquet. There are two parts to writing a parquet,
the first is creating the table. This is where the schema needs to be passed in. Below is the code from pandas 0.25 without support.

```python
if index is None:
    from_pandas_kwargs = {}
else:
	from_pandas_kwargs = {"preserve_index": index}
table = self.api.Table.from_pandas(df, **from_pandas_kwargs)
```

the second is writing the table

```python
self.api.parquet.write_table(
                table,
                path,
                compression=compression,
                coerce_timestamps=coerce_timestamps,
                **kwargs,
            )
```
			
The [fix](https://github.com/ieaves/pandas/blob/9cb2332ef54d3010e88994349e1ff21dba3d4736/pandas/io/parquet.py#L94-L115) in pandas 1.0 to enforce writing a schema was to allow it to be passed through the kwargs. It would then be pulled out from the dictionary and used in thepyarrow Table creation. Code snippet shown below:

``` python
from_pandas_kwargs: Dict[str, Any] = {"schema": kwargs.pop("schema", None)}
if index is not None:
	from_pandas_kwargs["preserve_index"] = index

table = self.api.Table.from_pandas(df, **from_pandas_kwargs)
```

That brings us to the fugue _save_parquet behavior. For pandas 0.25, the schema argument is not pulled out, meaning it continues on to the `parquet.write_table` method.

`write_table` uses the [ParquetWriter](http://arrow.apache.org/docs/python/generated/pyarrow.parquet.ParquetWriter.html) class, which has a positional argument named `schema`. This means that because `schema` is still left in `kwargs`, it causes a conflict where `schema` is defined by both a positional argument and a keyword argument.

I don't think there is a fix for this. The `schema` argument really needs to be named `schema` to use it with pandas 1.0. Even if we somehow got the error to stop showing, it's still going to cause unexpected behavior because pandas 0.25 can't support enforcing schema. I guess the only thing to do here is to require pandas 1.0

**Comment by kvnkho** [comment] 2020-10-04 22:53
I ran the unit tests with pandas==0.25 to see how many were failing. The test suite actually interrupts because there is an import error.

The traceback is:
`
tests\fugue\workflow\test_workflow_parallel.py:1: in <module>
    from fugue import FugueWorkflow, DataFrame, NativeExecutionEngine
fugue\__init__.py:16: in <module>
    from fugue.execution.native_execution_engine import NativeExecutionEngine, SqliteEngine
fugue\execution\__init__.py:3: in <module>
    from fugue.execution.native_execution_engine import NativeExecutionEngine, SqliteEngine
fugue\execution\native_execution_engine.py:25: in <module>
    from qpd_pandas.engine import PandasUtils
..\..\..\anaconda3\envs\f-dev2\lib\site-packages\qpd_pandas\__init__.py:3: in <module>
    from qpd_pandas.engine import QPDPandasEngine, run_sql_on_pandas
..\..\..\anaconda3\envs\f-dev2\lib\site-packages\qpd_pandas\engine.py:5: in <module>
    from pandas.core.window.indexers import BaseIndexer
E   ModuleNotFoundError: No module named 'pandas.core.window.indexers'; 'pandas.core.window' is not a package
`

It's failing because pandas.core.window is only present in pandas 1.0

**Comment by goodwanghan** [comment] 2020-10-05 02:12
This is a good point, so i guess we have to say we only support pandas>=1.0.2

Thanks for the investigation!

**Closed** 2020-10-05 03:01 UTC
Labels: bug, version dependent
